---
- name: Dump
  hosts: "{{ target|default('localhost') }}"
  tasks:
    - name: Facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - os_family
          - platform
      register: facts
    - name: Debug
      ansible.builtin.debug:
        var: facts.ansible_facts
