---
- name: Dump
  hosts: stage
  connection: local
  tasks:
    - ansible.builtin.debug:
        msg: "--==[[ STAGING ]]==--"
    - name: Facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - os_family
          - platform
      register: facts
    - name: Debug
      ansible.builtin.debug:
        var: facts.ansible_facts
